# The URL the site will be built for
base_url = "https://github.com/GalAster/sora.github.io"
theme = "mikoto"
description = ""
compile_sass = true
slugify-path = true
highlight_code = true
highlight_theme = "monokai"
taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
    # {name = "series", rss = true},
]

[extra]
author = "Aster"
favicon = "avatar.jpg"
github_link = "https://github.com/GalAster/sora.github.io"

aplayer_enable = true

